#ifndef __LF_PLAY_OBJECT_H__
#define __LF_PLAY_OBJECT_H__

#include "lf_platform.h"
#include "lf_struct.h"

namespace LF
{
	// TPlayObject 人物对象，继承TSmartObject
	class PlayObject
	{
	public:
		explicit PlayObject(struct TPlayObjectFunc* self);
		virtual ~PlayObject();
	public:
		bool GetUserID(struct TPlayObject* object, char* dest, u32* destLen);
		bool GetIPAddr(struct TPlayObject* object, char* dest, u32* destLen);
		bool GetIPLocal(struct TPlayObject* object, char* dest, u32* destLen);
		bool GetMachineID(struct TPlayObject* object, char* dest, u32* destLen);
		bool GetIsReadyRun(struct TPlayObject* object);
		bool GetLogonTime(struct TPlayObject* object, PSYSTEMTIME logonTime);
		i32 GetSoftVerDate(struct TPlayObject* object);
		i32 GetClientType(struct TPlayObject* object);
		bool IsOldClient(struct TPlayObject* object);
		i16 GetScreenWidth(struct TPlayObject* object);
		i16 GetScreenHeight(struct TPlayObject* object);
		i16 GetClientViewRange(struct TPlayObject* object);
		u8 GetRelevel(struct TPlayObject* object);
		void SetRelevel(struct TPlayObject* object, u8 value);
		i32 GetBonusPoint(struct TPlayObject* object);
		void SetBonusPoint(struct TPlayObject* object, i32 value);
		void SendAdjustBonus(struct TPlayObject* object);
		bool GetHeroName(struct TPlayObject* object, char* dest, u32* destLen);
		bool GetDeputyHeroName(struct TPlayObject* object, char* dest, u32* destLen);
		u8 GetDeputyHeroJob(struct TPlayObject* object);
		struct THeroObject* GetMyHero(struct TPlayObject* object);
		bool GetFixedHero(struct TPlayObject* object);
		void ClientHeroLogOn(struct TPlayObject* object, bool isDeputyHero);
		bool GetStorageHero(struct TPlayObject* object);
		bool GetStorageDeputyHero(struct TPlayObject* object);
		bool GetIsStorageOpen(struct TPlayObject* object, i32 index);
		void SetIsStorageOpen(struct TPlayObject* object, i32 index, bool value);
		u64 GetGold(struct TPlayObject* object);
		void SetGold(struct TPlayObject* object, u64 value);
		u64 GetGoldMax(struct TPlayObject* object);
		bool IncGold(struct TPlayObject* object, u64 value);
		bool DecGold(struct TPlayObject* object, u64 value);
		void GoldChanged(struct TPlayObject* object);
		u64 GetGameGold(struct TPlayObject* object);
		void SetGameGold(struct TPlayObject* object, u64 value);
		void IncGameGold(struct TPlayObject* object, u64 value);
		void DecGameGold(struct TPlayObject* object, u64 value);
		void GameGoldChanged(struct TPlayObject* object);
		u64 GetGamePoint(struct TPlayObject* object);
		void SetGamePoint(struct TPlayObject* object, u64 value);
		void IncGamePoint(struct TPlayObject* object, u64 value);
		void DecGamePoint(struct TPlayObject* object, u64 value);
		u64 GetGameDiamond(struct TPlayObject* object);
		void SetGameDiamond(struct TPlayObject* object, u64 value);
		void IncGameDiamond(struct TPlayObject* object, u64 value);
		void DecGameDiamond(struct TPlayObject* object, u64 value);
		void NewGamePointChanged(struct TPlayObject* object);
		u64 GetGameGird(struct TPlayObject* object);
		void SetGameGird(struct TPlayObject* object, u64 value);
		void IncGameGird(struct TPlayObject* object, u64 value);
		void DecGameGird(struct TPlayObject* object, u64 value);
		u64 GetGameGoldEx(struct TPlayObject* object);
		void SetGameGoldEx(struct TPlayObject* object, u64 value);
		u64 GetGameGlory(struct TPlayObject* object);
		void SetGameGlory(struct TPlayObject* object, u64 value);
		void IncGameGlory(struct TPlayObject* object, u64 value);
		void DecGameGlory(struct TPlayObject* object, u64 value);
		void GameGloryChanged(struct TPlayObject* object);
		u64 GetPayMentPoint(struct TPlayObject* object);
		void SetPayMentPoint(struct TPlayObject* object, u64 value);
		u64 GetMemberType(struct TPlayObject* object);
		void SetMemberType(struct TPlayObject* object, u64 value);
		u64 GetMemberLevel(struct TPlayObject* object);
		void SetMemberLevel(struct TPlayObject* object, u64 value);
		i16 GetContribution(struct TPlayObject* object);
		void SetContribution(struct TPlayObject* object, i16 value);
		void IncExp(struct TPlayObject* object, u32 value);
		void SendExpChanged(struct TPlayObject* object);
		void IncExpNG(struct TPlayObject* object, u32 value);
		void SendExpNGChanged(struct TPlayObject* object);
		void IncBeadExp(struct TPlayObject* object, u32 value, bool isFromNPC);
		i32 GetVarP(struct TPlayObject* object, i32 index);
		void SetVarP(struct TPlayObject* object, i32 index, i32 value);
		i32 GetVarM(struct TPlayObject* object, i32 index);
		void SetVarM(struct TPlayObject* object, i32 index, i32 value);
		i32 GetVarD(struct TPlayObject* object, i32 index);
		void SetVarD(struct TPlayObject* object, i32 index, i32 value);
		u64 GetVarU(struct TPlayObject* object, i32 index);
		void SetVarU(struct TPlayObject* object, i32 index, u64 value);
		bool GetVarT(struct TPlayObject* object, i32 index, char* dest, u32* destLen);
		void SetVarT(struct TPlayObject* object, i32 index, const char* value);
		u64 GetVarN(struct TPlayObject* object, i32 index);
		void SetVarN(struct TPlayObject* object, i32 index, u64 value);
		bool GetVarS(struct TPlayObject* object, i32 index, char* dest, u32* destLen);
		void SetVarS(struct TPlayObject* object, i32 index, const char* value);
		struct TList* GetDynamicVarList(struct TPlayObject* object);
		i32 GetQuestFlagStatus(struct TPlayObject* object, i32 nFlag);
		void SetQuestFlagStatus(struct TPlayObject* object, i32 nFlag, i32 value);
		bool IsOffLine(struct TPlayObject* object);
		bool IsMaster(struct TPlayObject* object);
		bool GetMasterName(struct TPlayObject* object, char* dest, u32* destLen);
		struct TPlayObject* GetMasterHuman(struct TPlayObject* object);
		i32 GetApprenticeNO(struct TPlayObject* object);
		struct TList* GetOnlineApprenticeList(struct TPlayObject* object);
		struct TList* GetAllApprenticeList(struct TPlayObject* object);
		bool GetDearName(struct TPlayObject* object, char* dest, u32* destLen);
		struct TPlayObject* GetDearHuman(struct TPlayObject* object);
		u8 GetMarryCount(struct TPlayObject* object);
		struct TPlayObject* GetGroupOwner(struct TPlayObject* object);
		struct TStringList* GetGroupMembers(struct TPlayObject* object);
		bool GetIsLockLogin(struct TPlayObject* object);
		void SetIsLockLogin(struct TPlayObject* object, bool value);
		bool GetIsAllowGroup(struct TPlayObject* object);
		void SetIsAllowGroup(struct TPlayObject* object, bool value);
		bool GetIsAllowGroupReCall(struct TPlayObject* object);
		void SetIsAllowGroupReCall(struct TPlayObject* object, bool value);
		bool GetIsAllowGuildReCall(struct TPlayObject* object);
		void SetIsAllowGuildReCall(struct TPlayObject* object, bool value);
		bool GetIsAllowTrading(struct TPlayObject* object);
		void SetIsAllowTrading(struct TPlayObject* object, bool value);
		bool GetIsDisableInviteHorseRiding(struct TPlayObject* object);
		void SetIsDisableInviteHorseRiding(struct TPlayObject* object, bool value);
		bool GetIsGameGoldTrading(struct TPlayObject* object);
		void SetIsGameGoldTrading(struct TPlayObject* object, bool value);
		bool GetIsNewServer(struct TPlayObject* object);
		bool GetIsFilterGlobalDropItemMsg(struct TPlayObject* object);
		void SetIsFilterGlobalDropItemMsg(struct TPlayObject* object, bool value);
		bool GetIsFilterGlobalCenterMsg(struct TPlayObject* object);
		void SetIsFilterGlobalCenterMsg(struct TPlayObject* object, bool value);
		bool GetIsFilterGolbalSendMsg(struct TPlayObject* object);
		void SetIsFilterGolbalSendMsg(struct TPlayObject* object, bool value);
		bool GetIsPleaseDrink(struct TPlayObject* object);
		i32 GetIsDrinkWineQuality(struct TPlayObject* object);
		void SetIsDrinkWineQuality(struct TPlayObject* object, i32 value);
		i32 GetIsDrinkWineAlcohol(struct TPlayObject* object);
		void SetIsDrinkWineAlcohol(struct TPlayObject* object, i32 value);
		bool GetIsDrinkWineDrunk(struct TPlayObject* object);
		void SetIsDrinkWineDrunk(struct TPlayObject* object, bool value);
		void MoveToHome(struct TPlayObject* object);
		void MoveRandomToHome(struct TPlayObject* object);
		void SendSocket(struct TPlayObject* object, struct TDefaultMessage* defMsg, const char* sMsg);
		void SendDefMessage(struct TPlayObject* object, i16 wIdent, i64 nRecog, i16 nParam, i16 nTag, i16 nSeries, const char* sMsg);
		void SendMoveMsg(struct TPlayObject* object, const char* sMsg, u8 btFColor, u8 btBColor, i16 nY, i32 nMoveCount, i32 nFontSize, i32 nMarqueeTime);
		void SendCenterMsg(struct TPlayObject* object, const char* sMsg, u8 btFColor, u8 btBColor, i32 nTime);
		bool SendTopBroadCastMsg(struct TPlayObject* object, const char* sMsg, u8 btFColor, u8 btBColor, i32 nTime, i32 msgType);
		bool CheckTakeOnItems(struct TPlayObject* object, i32 where, struct TStdItem* stdItem);
		void ProcessUseItemSkill(struct TPlayObject* object, i32 where, struct TStdItem* stdItem, bool isTakeOn);
		void SendUseItems(struct TPlayObject* object);
		void SendAddItem(struct TPlayObject* object, struct TUserItem* userItem);
		void SendDelItemList(struct TPlayObject* object, const char* items, i32 itemsCount);
		void SendDelItem(struct TPlayObject* object, struct TUserItem* userItem);
		void SendUpdateItem(struct TPlayObject* object, struct TUserItem* userItem);
		void SendItemDuraChange(struct TPlayObject* object, i32 itemWhere, struct TUserItem* userItem);
		void SendBagItems(struct TPlayObject* object);
		void SendJewelryBoxItems(struct TPlayObject* object);
		void SendGodBlessItems(struct TPlayObject* object);
		void SendOpenGodBlessItem(struct TPlayObject* object, i32 index);
		void SendCloseGodBlessItem(struct TPlayObject* object, i32 index);
		void SendUseMagics(struct TPlayObject* object);
		void SendAddMagic(struct TPlayObject* object, struct TUserMagic* userMagic);
		void SendDelMagic(struct TPlayObject* object, struct TUserMagic* userMagic);
		void SendFengHaoItems(struct TPlayObject* object);
		void SendAddFengHaoItem(struct TPlayObject* object, struct TUserItem* userItem);
		void SendDelFengHaoItem(struct TPlayObject* object, i32 index);
		void SendSocketStatusFail(struct TPlayObject* object);
		void PlayEffect(struct TPlayObject* object, i32 nFileIndex, i32 nImageOffset, i32 nImageCount, i32 nLoopCount, i32 nSpeedTime, u8 btDrawOrder, i32 nOffsetX, i32 nOffsetY);
		bool IsAutoPlayGame(struct TPlayObject* object);
		bool StartAutoPlayGame(struct TPlayObject* object);
		bool StopAutoPlayGame(struct TPlayObject* object);
	private:
		struct TPlayObjectFunc* self;
		struct TPlayObject*		object;
	};
}
#endif // __LF_PLAY_OBJECT_H__